version: '2'

networks:
  extnet:
    external: true

services:
  samba:
    image: qhuy199/samba-domain
    container_name: samba
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/docker/containers/samba/data/:/var/lib/samba
      - /data/docker/containers/samba/config/samba:/etc/samba/external
    environment:
      - DOMAIN=CORP.EXAMPLE.COM
      - DOMAINPASS=P@ssw0rd
      - DNSFORWARDER=8.8.8.8
      - HOSTIP=192.168.1.79
    networks:
      - extnet
    ports:
      - 192.168.1.79:53:53
      - 192.168.1.79:53:53/udp
      - 192.168.1.79:88:88
      - 192.168.1.79:88:88/udp
      - 192.168.1.79:135:135
      - 192.168.1.79:137-138:137-138/udp
      - 192.168.1.79:139:139
      - 192.168.1.79:389:389
      - 192.168.1.79:389:389/udp
      - 192.168.1.79:445:445
      - 192.168.1.79:464:464
      - 192.168.1.79:464:464/udp
      - 192.168.1.79:636:636
      - 192.168.1.79:1024-1044:1024-1044
      - 192.168.1.79:3268-3269:3268-3269
    dns_search:
      - corp.example.com
    dns:
      - 192.168.1.79
      - 8.8.8.8
    extra_hosts:
      - localdc.corp.example.com:192.168.1.79
    hostname: localdc
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    privileged: true
    restart: always

# ----------- samba end ----------- #
