version: '3.8'

networks:
  samba:
    external: true

services:
  samba:
    image: qhuy199/samba-domain
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/docker/containers/samba/data/:/var/lib/samba
      - /data/docker/containers/samba/config/samba:/etc/samba/external
    environment:
      - DOMAIN=CORP.EXAMPLE.COM
      - DOMAINPASS=ThisIsMyAdminPassword
      - DNSFORWARDER=8.8.8.8
      - HOSTIP=192.168.1.79
    networks:
      - samba
    ports:
      - 53:53
      - 53:53/udp
      - 88:88
      - 88:88/udp
      - 135:135
      - 137-138:137-138/udp
      - 139:139
      - 389:389
      - 389:389/udp
      - 445:445
      - 464:464
      - 464:464/udp
      - 636:636
      - 1024-1044:1024-1044
      - 3268-3269:3268-3269
    dns_search:
      - corp.example.com
    dns:
      - 192.168.1.79
      - 8.8.8.8
    extra_hosts:
      - localdc.corp.example.com:192.168.1.79
    hostname: localdc
#    cap_add:
#    #      - NET_ADMIN
#    #    devices:
#    #      - /dev/net/tun
#    #    privileged: true
#    #    restart: always
#
#    # ----------- samba end ----------- #
#
